name: Rust

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    environment:
      name: krk-rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --locked
    - name: Run tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: cargo test --test api
